spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Dheeraj@99
  application:
    name: coupon-service


#dataconfig:
#  url: jdbc:mysql://localhost:3306/test
#  username: root
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/

#  password: Dheeraj@99